analogdevicesinc/iio-oscilloscope

osc.c
This enables auto-connecting to a remote iiod session running at an IP address specified in an ini file.
=> osc: support "remote_ip_addr" field in the main profile section

plugins/block_diagram.h, plugins/fmcomms2.c, plugins/fmcomms2_adv.c, plugins/fmcomms5.c
For some reason, under MinGW and when building for x86_64,
the pointers are 64-bit but the 'long' type is only 32-bit.
Go figure.
With this last commit applied, the OSC builds fine in MinGW with both the 32-bit and the 64-bit configurations.
=> Fix cast of pointers to integers of different size

Makefile, plugins/ad9361_multichip_sync.c, plugins/ad9361_multichip_sync.h, plugins/fmcomms2_adv.c
Factor out MCS so it can be used outside OSC as well.
=> plugins/ad9361_multichip_sync: Factor out MCS so it can be used outside

plugins/debug.c, plugins/dmm.c, plugins/fmcomms1.c, plugins/fmcomms2.c, plugins/fmcomms2_adv.c, plugins/fmcomms5.c, plugins/motor_control.c, plugins/pr_config.c
The plugins don't need to export anything else than the "plugin"
variable, except for the SCPI plugin.
This fixes a bug occuring on Windows, where the fmcomms1 plugin would
never load.
Signed-off-by: Paul Cercueil <paul.cercueil@analog.com>
=> Staticify the functions of the plugins (except SCPI)

plugins/fmcomms2.c, plugins/scpi.c
Note that this requires the latest changes to fru_tools (the -t option for fru-dump) to be able to save values to the EEPROM properly.
=> Add support for writing/reading EEPROM tuning params

plugins/fmcomms2_adv.c
in_voltage_quadrature_tracking_en does not exist as an attribute.  Changed to quadrature_tracking_en.
=> Changed in_voltage_quadrature_tracking_en

Makefile
* iterate over all dependencies to find out which one is missing ; pkg-config is a all-or-nothing method ; so if any dependency is missing, it will always point to glib as not being found
* dependency check is the first build step ; this has been made sure to run as first even for multi-job builds
* Added checks for `matio` and `libad9361-iio` to dep check
=> build: fix & update dependency checks

oscplot.c
These were found by enabling some extra checks for the compiler.
They are small bugs that should be fixed.
=> oscplot.c: fix/add omitted break statements

Makefile
Fixes: https://github.com/analogdevicesinc/iio-oscilloscope/issues/72
Fixes: https://github.com/analogdevicesinc/iio-oscilloscope/issues/79
Order/preference is: /usr/lib64, /usr/lib, /usr/lib32.
Suggestion came from Edward Kigwana on Github issue #79.
This should handle most standard cases/setups.
For the exotic cases, there's usually not much we can do anyway.
Handling multi-arch setups is not always straightforward on all distros and
the simplest way is to organize linker search paths, so that one has a
preference over the other.
=>  build: organize linker search paths in LDFLAGS

plugins/scpi.c
Fixes https://github.com/analogdevicesinc/iio-oscilloscope/issues/71
The `scpi_rx_setup()` function does not take any args, but it's called
with one.
The compiler does not seem to complain, especially when checks are a bit lax.
And even though this is not a problem (functionally), it is incorrect (a
bug). This fixes it.
=> plugins/scpi: remove argument in scpi_rx_setup() call

plugins/fmcomms5.c
The fmcomms5 platform uses a 128-bit transmit data bus and hence requires a
16 byte size alignment on transmit waveform data.
The default alignment is 8 bytes. If a waveform is only 8 bytes aligned and
not 16 byte this will cause the last 8 bytes of the waveform to be
truncated on the fmcomms5 platform causing a discontinuity.
To fix this properly configure the required alignment in the fmcomms5
plugin.
=> fmcomms5: Fix DAC data alignment

plugins/daq2.c
The daq2 platform uses a 128-bit transmit data bus and hence requires a 16 byte
size alignment on transmit waveform data.
The default alignment is 8 bytes. If a waveform is only 8 bytes aligned and not
16 byte this will cause the last 8 bytes of the waveform to be truncated on the
daq2 platform causing a discontinuity.
To fix this properly configure the required alignment in the daq2 plugin.
=> daq2: Fix DAC data alignment

oscplot.c
At the moment the single tone marker harmonics get incorrectly computed for
negative frequencies as well as for harmonics that are beyond the second
Nyquist zone.
Fix this.
Tones will always appear modulus the sampling frequency and for real FFTs
tones in even Nyquist zones will appear mirrored.
=> oscplot: Fix single tone marker harmonics

dialogs.c, osc.c, oscplot.c
This changeset implements some changes reported in PR #97 , the Codacy tool and cppcheck.
This PR will fix them and in a later PR, the Codacy & cppcheck tools will be added to run over the code.
This project is being used as a test-bed for automating some code-review stuff, with the intent to simplify the effort for code reviews.
=> Code cleanups: part 1: implement cleanups from previous review, Codacy & cppcheck

oscplot.c
Build fails with g_type_class_add_private() being marked as deprecated.
https://travis-ci.org/analogdevicesinc/iio-oscilloscope/jobs/423795815
It fails on OS X, because libraries tend to be more up-to-date via
homebrew.
GLib provides a convenience macro to replace the g_type_class_add_private()
call. Then the G_TYPE_INSTANCE_GET_PRIVATE() needs to be replaced with
<type>_get_instance_private().
=> oscplot.c: remove deprecated code

oscplot.c
This PR takes a different approach to PR #105 
It initializes the `enabled_channel_mask` inside the `enabled_channels_of_device()` function, and re-uses the `num_enabled` in `check_valid_setup_of_device()` to save some cycles.
=> rework check_valid_setup_of_device() logic

plugins/ad9371.c, plugins/ad9739a.c, plugins/adrv9009.c, plugins/daq2.c, plugins/fmcomms1.c, plugins/fmcomms11.c, plugins/fmcomms2.c, plugins/fmcomms5.c, plugins/motor_control.c, plugins/pr_config.c, plugins/scpi.c
Replace the sequence of
snprintf(buf, ...);
fwrite(buf, ..., f);
with
fprintf(f, ...);
This is semantically equivalent for the most part but removes the need for
a temporary buffer. This new solution differs in that the data written is
not truncated if it exceeds the size of the original temporary buffer.
Bulk of the transformation was done using the following coccinelle semantic
patch:
// <smpl>
@@
expression buf;
expression len;
expression f;
@@
+fprinf(f,
-snprintf(buf, len,
...);
-fwrite(buf, ..., f);
// </smpl>
=> Replace snprintf() + fwrite() with fprintf()

Makefile
This allows building osc on the embedded Ubuntu image. The makefile based
build will be dropped soon in favor of the cmake based build. But for
now make sure we can build OSC on our embedded targets.
=> Makefile: Remove serial backend to allow building on the SD card image

osc.c
When the plugins are compiled under macOS, they are created with a ".dylib" extension. However the code which currently loads the plugins, caters only for Windows ".dll" and Linux ".so" files. The modest code change in this PR now makes it possible for the plugins to be loaded on macOS devices.
=> Added preprocessor condition to provide access to plugins under macOS.

compat.h, dialogs.c, osc.c, xml_utils.c
Fixes #120 
On some file-systems, the `d_type` may be invalid/un-populated.
These mixes are a bit rare/esoteric, and [in such cases] we can assume
that the files are regular, because the information is invalid.
Normally these bugs would be in the filesystem or libc, but it's trivial to
handle them here as well.
=> osc: assume a file regular if d_type is 0

CMakeLists.txt, Makefile, glade/adrv9009.glade, iio_utils.c, iio_utils.h, plugins/adrv9009.c
Refactors the ADRV9009 plugin to work with multiple adrv9009-phy devices (adrv9009-phy, adrv9009-phy-b, adrv9009-phy-c, etc.)
The main logic in this refactor is to create a structure that corresponds to each adrv9009-phy device and therefore move all static variables in this structure.
Also all methods that were previously assuming only one device exists, are now refactored to handle multiple devices.
The widgets for the 2nd, 3rd, etc. device are all taken from the same .glade file but the widgets are loaded through a different gtk builder. The .glade file will continue to look the same (as it was for one device only) and tabs will be dynamically created, in the plugin, for any extra device.
The advanced plugin is not in this PR. It will be in a separate one.
=> Multiple adrv9009 plugin no adv

CMakeLists.txt
This PR enables brew builds against local libiio and libad9361 installs.
Formula for brew install: https://github.com/tfcollins/homebrew-formulae/blob/master/i-i-o-oscilloscope.rb
Signed-off-by: Travis Collins <travis.collins@analog.com>
=> Add macOS brew support

glade/adrv9009.glade
The TX can be disabled and in this case the AUX PLL LO frequency will be 0. Therefore we remove the lower limit of the spin button (which was 70 Meg) otherwise the plugin when reads 0 will force the widget to 70 Meg and write back to the driver. And this is not desired.
=> plugins/adrv9009: Lower the lower bound of the AUX PLL LO freq to zero

dialogs.c
This was a function added in libiio 0.9, so use it to test things.
I think this was causing random crashes on Windows, and this will be
safer.
Signed-off-by: Robin Getz <robin.getz@analog.com>
=> dialogs: use iio_has_backend to test for usb backend suppport

plugins/adrv9009.c, plugins/dac_data_manager.c
Fixes https://github.com/analogdevicesinc/iio-oscilloscope/issues/138
dac_data_manager_set_dds_mode() and dac_data_manager_get_dds_mode() need tx_index to start from 1 and not 0.
=> Save/Restore: Fix saving/restoring the 'DDS mode'

osc.c
Commit e0bad3c7e7d6907ee72a7173fb94cdb4d7e513a0 removed void typecasting.
From memmove() reference, the src and dest parameters need to be typecasted
to void
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> osc.c: Fix freeze for osc trigger

datatypes.h, oscplot.c, oscplot.h
When initializing a FFT plot, plot_setup initializes the transform
as well as the X and Y axis and passes the handles to the gtkdatabox library.
After initialization osc_plot_update_rx_lbl is called which calls transform_setup,
invalidating the handles sent to the gtkdatabox. This causes gtkdatabox to apply
operations on invalid memory areas. To fix this, we make sure we don't reinitialize
the transform on initial setup.
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> oscplot: fix memory corruption in plot_setup()

Makefile
The uninstall target was not removing adi-osc.desktop correctly.
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>
=> make: Fix uninstall target

plugins/adrv9009.c
In case the HMC7044 is not used, skip single shot mode workaround.
The AD9528 won't need this anyways. Hide the MCS button in single device
mode. This addresses issue #148
=> plugins/adrv9009: Hide MCS for single device usage and be less verbose

plugins/adrv9009.c
In case the HMC7044 is not used, skip single shot mode workaround.
The AD9528 won't need this anyways. Hide the MCS button in single device
mode. This addresses issue #148
=> [2018_R2] plugins/adrv9009: Hide MCS for single device usage and be less verbose

eeprom.c
Remove free() call which could lead to a possible segmentation fault.
The first time find_eeprom() is called, eeprom_path is NULL. Either way,
must be the caller responsibility to free the allocated memory.
Signed-ooff-by: Nuno Sa <Nuno.Sa@analog.com>
=> eeprom: Fix possible segfault

CMakeLists.txt, adi-osc.desktop.cmakein, org.adi.pkexec.osc.policy.cmakein
This PR aims to fix #102. It also configures and installs an adi-osc.desktop file when using cmake. Also note that, the polkit action is only being supported on cmake builds....
=> Fix gksu deprecated

osc.c, osc.h, oscplot.c
Changing resolutions/monitor setup should no longer result in hidden windows.
Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>
=> osc.c: add safeguard to load window positions only if they are on screen

.travis.yml, CI/travis/make_darwin, CI/travis/make_linux
Error is:
```
--   Package 'libffi', required by 'gobject-2.0', not found
CMake Error at /usr/local/Cellar/cmake/3.14.0/share/cmake/Modules/FindPkgConfig.cmake:457 (message):
```
Fix this by providing the correct PKG_CONFIG_PATH for libffi.
Also splitting a `make_darwin` file from `make_linux`.
This is to assign the MacOS X specific env-var to the build.
=> CI/travis: fix build with OS X

plugins/fmcomms2.c, plugins/fmcomms2_adv.c, profiles/AD-FREQCVT1_test.ini, profiles/AD-TRXBOOST1_test.ini, profiles/ADRV9363_test.ini, profiles/FMComms2_sweep.ini, profiles/FMComms2_test.ini, profiles/FMComms4_sweep.ini, profiles/FMComms4_test.ini, profiles/FMComms5_test.ini, profiles/GSM.ini, profiles/LTE10.ini, profiles/LTE15.ini, profiles/LTE1p4.ini, profiles/LTE20.ini, profiles/LTE3.ini, profiles/LTE5.ini, profiles/PZSDR1_test.ini, profiles/PZSDR2_2400TDD_test.ini, profiles/PZSDR2_test.ini
Rename FMComms2 tabs to AD936X to address #147. Test ini files have been updated as well with this new naming.
Signed-off-by: Travis Collins <travis.collins@analog.com>
=> Rename FMComms2 tabs to AD936X

plugins/adrv9009_adv.c
This seems to be something about which GCC 8 complains about:
```
plugins/adrv9009_adv.c:924:72: error: cast between incompatible function types from 'void (*)(void *)' to 'void (*)(void *, GClosure *)' {aka 'void (*)(void *, struct _GClosure *)'} [-Werror=cast-function-type]
G_CALLBACK(signal_handler_cb), data_to_pass, (GClosureNotify)g_free, 0);
```
This wasn't happening before.
It is a good warning, as it can cause stack corruption.
=> plugins: adrv9009_adv: assign correct clojure callback

plugins/adrv9009.c
=> plugins/adrv9009: MCS remove redundant SPI write and add comment

Makefile, glade/cn0508.glade, plugins/CMakeLists.txt, plugins/cn0508.c
This is an initial revision for the cn0508. This is a desktop power supply
based on the ad7124-8 adc and ad5683r dac. This plugin will enable the use
of the power supply over the network, to set different voltage and current
ranges.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
=> plugin: cn0508: Initial revision for cn0508

.travis.yml
Trusty is 5 years old now.
And since this year, Ubuntu Xenial 16.04 is the default in Travis-CI:
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
=> build: retire/remove trusty builds

datatypes.h, oscplot.c, plugins/lidar.c
For the LIDAR project, the "voltage4" channel needs to be always enabled when capturing data and displaying it on the plot.
These changes set channel "voltage4" to ON and make it grey-out to prevent disabling it.
=> Plot channels constraints

CMakeLists.txt, Makefile, osc.c, osc_plugin.h, osc_preferences.c, osc_preferences.h, oscplot.c, oscplot.h, plugins/fmcomms2.c, plugins/lidar.c
Add a system for the plugins to send their preferences to the osc and the osc plot.
The idea is to have a straight forward way to exchange this kind of data.
All preferences are collected by osc and merged (if no conflicts). Then the preferences are use throughout the application.
Examples of preferences:
- default value of sample count when creating a plot window
- constraints for some channels to be always checked in the plot window
- constraints for some channels to be un-toggleable in the plot window
- additional FFT correction to be used for a specific iio-device
Other preferences might come up in the future
=> Osc preferences

oscplot.c
=> oscplot: Fix message that says correlation needs 2 channels (needs 4)

CI/travis/make_darwin
OS X's glib is upgrading way too fast/often.
Now it's complaining with some deprecation stuff.
Export a CFLAGS option to ignore this.
=> build,os-x: ignore deprecated warnings

plugins/dac_data_manager.c
The generic initialization of ddac->txs overwrites the other one which is made in the special case when tx_count == 0.
This fixes segfault when loading FMComms11 and most likely Ad9739A (and any other board that matches the special case consiguration where tx_count == 0).
=> plugins/dac_data_manager: Don't overwrite already initialized things

.travis.yml
iio-oscilloscope does not have any relation (directly & dependency-wise) to
Matlab (or other Mathworks tools).
So, we can choose to drop support for Xcode 9 now.
Since support for Xcode 11 has been recently added, it's probably a good
idea to also remove support for Xcode 9.
=> build,travis-ci: drop support for Xcode 9

.travis.yml, CI/travis/pre_build_checks, NOTE_FOR_DEVELOPERS.txt, dev-tools/fixup-all-glades.sh, dev-tools/fixup-comboboxtext.pl, dev-tools/fixup-gtk3-glade.sh, glade/ad9371.glade, glade/ad9371_adv.glade, glade/adrv9009.glade, glade/adrv9009_adv.glade, glade/fmcomms11.glade, glade/fmcomms2.glade, glade/lidar.glade, glade/osc.glade, glade/spectrum_analyzer.glade
Recently, we've stopped using some deprecated methods of GtkComboBox and started using the recommended methods that belong to class GtkComboBoxText.
However, GtkComboBoxText objects that are loaded from glade files do not function properly.
GtkComboBoxText has a bug that makes it unsuable (can't get the active text, or insert new text, etc.). In order to work, instances of GtkComboBoxText need the property "entry-text-column" >= 0, which doesn't happen when a GtkComboBoxText is obtained from a glade file (creating them with new works).
To fix this, there's now a script which can parse glade files and add the missing property.
An additional script has been added which should be used to fix glade files edited with Glade versions that target GTK3 and not GTK2.
=> Fix comboboxtext issue

CMakeLists.txt, adi-osc.desktop.cmakein, config.h.cmakein, glade/osc.glade, glade/oscplot.glade, osc-wrapper.cmakein
This series is mainly fixing the icons rendering for osc. The icons were just not being rendered in the app window (in window managers that render the icon on the windows). I'm not sure if this is the "best" way of doing this since I'm not really familiar on how apps usually ship this kind of UI elements. However, this PR has, at least, the goal of bringing the attention to this.
Moreover, there is a patch to not hardcode the `PREFIX` path to /usr/local and to fix the .desktop entry on some application launcher...
This series was tested in ubuntu18.04 and arch linux.
=> Misc fixes

config.h
The change introduced by 8afb45d ("build: config.h: Don't hardcode PREFIX
path") breaks the Makefile based build since there's no `config` header.
This can break some older builds that still rely on the Makefile build.
This patch restores the original file so that it works the same way it
used to work with make. When using cmake, this file will be overwritten
maintaining the behavior introduced by the mentioned patch.
=> build: Fix Makefile based build

CMakeLists.txt
This installs osc icons on the hicolor theme only for linux. Not doing so
was breaking macOs (and possibly Windows) when running `make install`.
=> build: Install icons on default theme only on linux

CI/travis/before_install_darwin, CI/travis/before_install_lib.sh, CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_darwin, CI/travis/make_linux
Tracing can be useful in debugging situations.
Remove it for normal builds, as it can be too much.
=> build,ci: remove tracing; reduce log output

CI/travis/before_install_darwin
This changeset tries to reduce the build time for OS X builds.
On average, it used to be 8 minutes on Xcode 10. With this changeset it's about 5, because some packages are not installed, because they are already present in the image provided by Travis-CI.
=> ci,os-x: reduce build times

iio_utils.h, plugins/debug.c
Provide larger buffers to store the content of iio attributes since 1024 isn't enough. Some attributes can be larger than that.
=> Fix buffer size reading attr

CI/travis/before_install_darwin
Homebrew has updated it's default `python` package to point at `python@3`.
Unfortunately, there is no clean way to fix this for osc. Or, I could not
find one.
When installing libmatio, it seems to pull `python@3`, and this seems to
conflict with python@2.
So, unlink it.
=> ci,osx: do brew unlink python@2 before installing packets

plugins/fmcomms2.c
=> plugins/fmcomms2: Fix sampling rate widget not displaying actual set val

CMakeLists.txt
Error reported here: https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/122371/make-fails-of-iio-oscilloscope---error-in-cmake-file
Signed-off-by: Travis F. Collins <travis.collins@analog.com>
=> Fix install paths for adi-osc icons

Makefile
Windows builds (and any other build that is made with Makefile instead of CMake) don't include the functionality to connect via Serial interface.
This PR fixes that.
=> makefile: Build with serial backend if libserialport is detected

plugins/dac_data_manager.c
Fix buffer TEXT file loading for tx channel counts > 8 and
channel counts which are not power of twos.
=> plugins/dac_data_manager: Fix buffer TEXT file loading

plugins/lidar.c
Before, it accepted negative only. Now accepts positive only.
=> plugins/lidar: Linux driver now accepts positive numbers for tilt

Makefile, glade/generic_plugin.glade, osc.c, osc_plugin.h, plugins/CMakeLists.txt, plugins/ad9371.c, plugins/ad9739a.c, plugins/adrv9009.c, plugins/daq2.c, plugins/fmcomms1.c, plugins/fmcomms11.c, plugins/fmcomms2.c, plugins/fmcomms5.c, plugins/generic_plugin.c
The generic plugin is used when no other plugin has been created and
provides a means of loading a data file and sending it as a buffer to a dac
device. It creates a gui panel for each device with dac properties.
Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
Signed-off-by: Cristian Pop <cristian.pop@analog.com>
=> plugins/generic_plugin: Initial version for a generic plugin

glade/fmcomms2_adv.glade
The issue was reported on: https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/163171/ad936x---typos-in-iio-oscilloscope
=> glade: fmcomms2_adv: Typo fix

osc.c
Similar to the rest of the plugins.
=> osc: Print loaded plugin information for generic_dac too

plugins/ad9081.c
plugins/ad9081.c: In function ‘select_page_cb’:
plugins/ad9081.c:73:38: error: comparison of integer expressions of
different signedness: ‘guint’ {aka ‘unsigned int’} and ‘gint’ {aka
‘int’} [-Werror=sign-compare]
if (!priv->has_once_updated && page == priv->this_page)
^~
=> plugins: ad9081: Fix different signedness comparison

plugins/ad9081.c
For consistency with the rest of the plugins, rename the plugin from
"ad9081" to "AD9081".
=> plugins: ad9081: Rename single device plugin name

plugins/ad9081.c
For preventing the generic_dac plugin to be loaded (since AD9081 has a
dedicated plugin), get_dac_dev_names() should be implemented.
=> plugins: ad9081: Implement get_dac_dev_names()

osc_plugin.h, plugins/ad9371.c, plugins/ad9739a.c, plugins/adrv9009.c, plugins/daq2.c, plugins/fmcomms1.c, plugins/fmcomms11.c, plugins/fmcomms2.c, plugins/fmcomms5.c, plugins/generic_dac.c
The parameter will be used when a plugin is instantiated multiple times.
=> plugins: Add osc_plugin parameter to get_dac_dev_names()

plugins/ad9081.c
This depends on https://github.com/analogdevicesinc/iio-oscilloscope/pull/236.
=> plugins: ad9081: Fix get_dac_dev_names() implementation

plugins/generic_dac.c
It can happen that the returned device name is NULL.
If that happens, the application will crash.
So, ignore the NULL.
=> plugins: generic_dac: ignore devices with no names

Makefile, glade/adrv9002.glade, plugins/CMakeLists.txt, plugins/adrv9002.c
This adds a plugin for the adrv9002 platform. It assumes more than one
device can exist so that the plugin is dynamically created
=> plugins: Add support for adrv9002

plugins/adrv9002.c
This patch fixes an opened file that might not be closed and a memleak in
the load_profile() function. It also removes an unused variable.
These fixes were to be added in last #242 but it was merged to quickly :smile:
=> plugins: adrv9002: Misc fixes

osc.c, osc.h
Check if the window fits the screen before moving it. If not move it to center.
Addresses #199
=> osc: Move windows to center as fallback

iio_utils.c
In case multiple devices are present we assume them sorted like this:
adrv9009-phy-d
adrv9009-phy-c
adrv9009-phy-b
adrv9009-phy-a
or
adrv9009-phy-d
adrv9009-phy-c
adrv9009-phy-b
adrv9009-phy
or
adrv9009-phy-3
adrv9009-phy-2
adrv9009-phy-1
adrv9009-phy-0
adrv9009-phy-3
adrv9009-phy-2
adrv9009-phy-1
adrv9009-phy
=> iio_utils: sort multiple devices

plugins/adrv9009.c
The current code crashes with ADRV9008-1, since not all IIO devices are
present on that board. This crashes on adrv9009_init().
Added null-checks.
=> plugins: adrv9009: fix crash with adrv9008-1

glade/osc.glade
This helps users when using the 'Manual URI' option to connect to a target.
Addresses #260
=> glade/osc: Add tooltip to connect dialog showing examples of URI

plugins/ad9371.c
Make sure the IIO contexts are valid before continuing.
In some cases different devicetree node names prevent the application
from starting because of a segmentation fault. fix it.
Signed-off-by: Liam Beguin <lvb@xiphos.com>
=> plugins: ad9371: check iio contexts during init

plugins/ad9371.c
The Up-Down converter devices are purely optional. Don't error
out in case they are not present.
This fixes
commit b38dbfe7e1a29 ("plugins: ad9371: check iio contexts during init")
=> plugins/ad9371: Fix plugin loading

osc.c, plugins/ad9081.c, plugins/adrv9002.c
The motivation for this was a crash provoked by a failure in initializing the adrv9002 plugin. If the plugins fails to initialize, it will do some cleanups and since this plugins provides `get_dac_dev_names()`, the generic_dac plugin will call it and thus, will try to access nonexistent data.
The reason why this is a RFC is because it's not clear to me if it is intentional that a plugin is kept around even if it fails to initialize. The natural thing to me is that if a plugin fails to initialize, then it should be removed from our plugin list and it's resources should also be cleaned....
With this change, it's clear that a plugin should not clear any data during the init callback (it might still choose to do so if it coordinates things with the `destroy()` callback). Hence, some plugins …
=> [RFC] plugin cleanup on init failure

osc.c, plugins/AD5628_1.c, plugins/AD7303.c, plugins/ad6676.c, plugins/ad9081.c, plugins/ad9371.c, plugins/ad9371_adv.c, plugins/ad9739a.c, plugins/adrv9002.c
This is the first PR to add some cleanups on the plugins `init()` callback. The fist patch actually reverts something that was added in #273 with respect with plugins cleanup. Basically, it makes only sense to call the plugin `destroy()` if it was successfully initialized. If not, its the plugin responsibility to free whatever it needs. This makes it more easier and simple to implement `destroy()` on the plugin side. The rest of the patches are doing some cleanups in case of plugin failures. Note that I'm not going into much detail in the plugins and so, I'm just fixing the more obvious leaks. This also has the goal to inherit less issues when doing `copy->pastes` for new plugins...
=> Plugins init cleanup 

CMakeLists.txt, config.h.cmakein
Several paths were hard-coded, which defied cmake's ability to work with
arbitrary installation paths.
Fixes a bug which defines GLADE_FILES_DEST but does not use it.
=> Fix installation paths and location of glade files / icons

Makefile, glade/cf_axi_tdd.glade, iio_utils.c, iio_utils.h, iio_widget.c, iio_widget.h, plugins/CMakeLists.txt, plugins/cf_axi_tdd.c
This PR adds some additions before actually adding the cf_axi_plugin driver:
* It makes some functions that are being widely used statically in plugins generic (to avoid more code duplication);
* It adds a new combo box API without refreshing every time the combo box available options so that we can do `widget->save() followed by widget->update()` without falling in an infinite loop;
* Blocks the gtk signals during widget->update().
The last point, which is the third patch is kind of a RFC patch. It's, arguably, a "nitpick" improvement. The point, is that when we update a widget, we can receive a different value from the iio dev from the one in the GUI (eg: a failed call to widget->save() or an autonomous update). In this case, we don't really want our widget signal handler to be called …
=> Plugin cf axi tdd

plugins/adrv9009.c
When FMCOMMS8 is used standalone, available devices are "adrv9009-phy-c"
and "adrv9009-phy-d". The previous implementation was searching exactly
for "adrv9009-phy".
=> plugins: adrv9009: Update plugin identify function for FMCOMMS8

glade/cn0540.glade, plugins/cn0540.c
With the latest hardware revision, the cn0540 blue led pin now doubles
as a constant courrent switch. This commit adds separate control for
this switch inside the cn0540 plugin.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>
=> plugins: cn0540: Add current source control

glade/adrv9002.glade, plugins/adrv9002.c
Add support to load a new stream binary in the plugin. It must be done
before loading the correspondent profile.
=> plugins: adrv9002: Support stream loading

dialogs.c
We should not make any max size assumptions from strings returned by
other libraries. Allow truncation using snprintf() to avoid buffer
overflows.
*** buffer overflow detected ***: terminated
A crash report file has been created at: /home/michael/.osc_crash_report
Segmentation fault (core dumped)
=> dialogs: Avoid buffer overflow

CI/travis/before_install_darwin, CI/travis/before_install_lib.sh, CI/travis/before_install_linux, CI/travis/lib.sh, CI/travis/make_darwin, CI/travis/make_linux, CMakeLists.txt, azure-pipelines.yml
This adds the first integration elements for building osc on Linux and Mac.
Windows builds require a bit more work to port, since we will need to re-visit all the dependencies and use Azure Windows images to build osc somehow.
Previously we were cross-building osc using Linux.
Also, this isn't deploying any artifacts yet.
This will require a bit more cmake work.
=> ci,azure-pipelines: add first integration with Azure (for Linux & Mac only right now)

glade/adrv9009.glade, plugins/adrv9009.c
This fixes issue:
DDS upper limit wrong on certain devices #289
=> plugins: adrv9009: Fix DDS upper limit bug

glade/oscplot.glade
Y{min/max} in time plot are only 16-bit values.
For 24-bit ADCs we need more range.
This fixes issue #274
=> glade: oscplot.glade: Fix Y{min/max} too small issue

osc.c
Plugins signal the oscplot as soon as the sampling frequency is changed (usually the control for the sampling frequency is available in the plugin).
However some ADCs might now have an associated plugin but sampling frequency could be changed by using the 'Debug' plugin or even outside of the application. For this scenario, we can't know instantly that the sampling frequency has changed but an improvement is to read the sampling frequency attribute of the ADC right before starting a capture.
This addresses #303
=> osc: Update sampling frequency of ADC when starting a capture

plugins/spectrum_analyzer.c
Otherwise this plugin will init and error out later.
In theory this shouldn't matter, but there is a yet to be fixed follow
on bug that we avoid with this fix.
=> plugins/spectrum_analyzer: Add the capture device as a dependency

osc.c
The commit 5ab930e ("osc: Close plugin if init() fails") closes a
plugin if it fails to initialize. However, this was only tested in
dynamically created plugins where there were no issues. However, it
crashes on static plugins because we get our plugin address using
`dlsym()`. Thus, we cannot really access our object after we do a
`dlclose()` on the library.
So, for static plugins, we need to ensure that `dlclose()` is the last
thing we do when closing the plugin. For dynamic plugins, as it was
allocated at runtime, we can (and we must) call `dlclose()` before we
`g_free()` the plugin. Obviously, we cannot free the plugin and then try
to use `plugin->handle` to close the library.
Signed-off-by: Nuno Sa <nuno.sa@analog.com>
=> osc: fix close_plugin() for static plugins

CMakeLists.txt, config.h.cmakein, profiles/AD-FREQCVT1_test.ini.cmakein, profiles/AD-TRXBOOST1_test.ini.cmakein, profiles/PZSDR2_2400TDD_test.ini.cmakein
polkit needs its own prefix:
- FHS distributions have polkit actions in /usr regardless of installation path
- non-FHS distributions don't and need this configurable
Convert profiles/*.ini files to *.cmakein when they reference other files and
need to honor CMAKE_INSTALL_PREFIX.
Fixes problems with #277
=> Fix installation paths

appveyor.yml
The artifacts stored in the appveyor build expire after 6 months. Since
the iio-osc-mingw gets rarely modified we're better off downloading the
dependecies from the artifacs section of the latest iio-osc-mingw
release.
=> CI/appveyor: Get the compiled dependencies from a Github release

plugins/adrv9002.c
Do not rearm the timer in case the profile fails to load. The plugin was
getting unresponsive in this situation. Moreover, it does not really make
sense to anything on the device if the profiles failed to load. Our only
choice is to try to load the profile again (or some other profile).
=> plugins: adrv9002: don't rearm the timer on profile failure

plugins/fmcomms11.c
This is required for the kernel driver change:
https://github.com/analogdevicesinc/linux/pull/1522
=> plugins/fmcomms11: Add support for the moved NCO frequency channel

plugins/adrv9002.c
This patch makes sure the dds gets into a consistent block with the rest
of the plugin (dds1 aligned with TX1 and dds2 with TX2). This is done by
checking the next character after the name "axi-adrv9002-tx" (as this is
the pattern we use to look for this devices). If we see a digit, then we
assume that it is the DDS2 and it should be under TX2 settings. If not a
digit, it's TX1. Naturally there's a chance for this to break if the
device name changes in some ways, but we do need to assume some "contracts"
with the name format otherwise this could get more complicated than it
needs to be.
=> [2019_R2] plugins: adrv9002: fix inconsistent labels under Transmit/DDS block

plugins/fmcomms5.c
This ensures that the two chips are initially synced.
=> SDGREL 447

plugins/fmcomms5.c
This ensures that the two chips are initially synced.
=> plugins/fmcomms5: MCS Sync devices after plugin init [SDGREL-447]

glade/adrv9002.glade, plugins/adrv9002.c
With the latest changes in the adrv9002 driver, if ORx is enabled, we won't
be able to change any control that might trigger an ensm change in
the RX/TX of the same channel as the enabled ORx. Hence, we control the
widgets sensitivity accordingly...
Special care is needed for tracking calibrations. The thing with tracking
cals is that, due to the way the device driver API/Firmware is designed, we
need to move all 4 ports to calibrated state to change a cal (even if we are
only changing cals in one specific port). Hence, we need to make sure that if
one of the ORxs is enabled, we block all the tracking calibrations controls
in all enabled ports.
Also to note that for things to work properly the glade file had to be
changed so that the ORx powerdown toggle is enabled by default. …
=> plugins: adrv9002: improve ORx handling

iio_utils.c, iio_utils.h, plugins/cf_axi_tdd.c
This is analogous to #323 . However in the 2019_R2 we need to handle IIO labels without direct support from libiio.
In the process, I found out an issue between plugins names and the devices that they are controlling (for dynamically created plugins; the commit message has more details). I included the patch on this PR so that the plugin is functional. However other plugins might also have the same problem. I will have to check and run some tests and potentially open a new PR to address the those.
=> [2019_R2] Fix axi tdd identification

iio_utils.c, osc.c, osc.h, plugins/ad9081.c, plugins/adrv9002.c, plugins/adrv9009_adv.c, plugins/cf_axi_tdd.c
This PR is result of the issues spotted in #340 . The first patch makes the string compare function (used for sorting devices) aware of IIO labels. The rest of the series is  handling the dynamic plugin name creation issue. This is done by introducing a new helper in osc to handle `get_data_for_possible_plugin_instances()`. As a bonus, we remove duplicated code used in all plugins supporting dynamic creation.
Also to note that adrv9002 and ad9081 were not affected by the plugin name issue because they were re-sorting the list of devices returned by `get_iio_devices_starting_with()`. With the new helper, there's no need for that anymore.
=> Misc fixes and improvements

dialogs.c, iio_utils.c, iio_utils.h, osc.c, plugins/debug.c
This adds support for IIO labels where needed for the adrv9002 eval boards. I first though I would grep for `iio_device_get_name()` and replace with the new helper introduced here but then I saw that maybe we do not need it in all places. Hence, let's introduce IIO labels "on demand".
Note that this will probably have to syn with #344
=> add iio label support for adrv9002 

plugins/ad9081.c
Don't compare Hz with MHz. This fixes a bug seen with the main NCO
adjustments.
=> plugins/ad9081: Fix MAX ADC/DAC frequency comparisons

plugins/adrv9002.c
We need to add the binary mode to 'fopen()' as it seems that windows treats
text files and binary files differently (on POSIX systems the b mode is
actually ignored). Otherwise, 'fread()' will actually return less bytes
than asked (with the size computed with fseek + ftell) and we will error
out before loading the stream. This fixes it and causes 'fread' to
return the expected number of bytes.
=> [2019_R2] plugins: adrv9002: fix profile configuration on windows

plugins/adrv9002.c
We need to add the binary mode to 'fopen()' as it seems that windows treats
text files and binary files differently (on POSIX systems the b mode is
actually ignored). Otherwise, 'fread()' will actually return less bytes
than asked (with the size computed with fseek + ftell) and we will error
out before loading the stream. This fixes it and causes 'fread' to
return the expected number of bytes.
=> plugins: adrv9002: fix profile configuration on windows

glade/adrv9002.glade, plugins/CMakeLists.txt, plugins/adrv9002.c
Add support for manipulating the BBDC loop gain. Since the 'round()'
function is being used in plugin, we need to also explicitly link against
-lm and not rely in some indirect linking.
=> plugins: adrv9002: support RX BBDC Loop gain

plugins/ad9081.c
In bypass/full bandwidth mode, channels are no longer complex IQ
modified. This patch adds support for this case.
=> plugins/ad9081: Support for bypass/full bandwidth mode

plugins/adrv9002.c
When the RX digital gain is set to automatic, the plugin was failing to
automatically update the gain. The reason is that the string to indicate
that the gain is automatic changed in the kernel driver from
automatic_control to automatic. This happened when moving to a newer API
version when it became clear that the digital gain ABI was being wrongly
"exported" by the driver and had to be fixed [1].
[1]: https://github.com/analogdevicesinc/linux/commit/63af6a270bb2b361cc5e0c152794a77614b34055
=> plugins: adrv9002: fix digital interface gain report

glade/xmw.glade, plugins/CMakeLists.txt, plugins/xmw.c
Add IIO-Osc plugin support for the xmicrowave board.
The plugin allows osc to manipulate the 2 upconverters, 2 downconverters
and the clock chip.
Signed-off-by: Antoniu Miclaus <antoniu.miclaus@analog.com>
=> plugins: add xmicrowave support

glade/dmm.glade, osc.c
Rebuild the DMM glade file with Glade 3.38.2.
This will make things easier if one wants to further modify the glade file. Also Glade 3.38.2 is the latest release at the moment and it targets UI files for GTK3 based applications.
Downsides:
- The "gtk-disconnect" stock icon is no longer available. I have used "window-new" icon instead. Also the icon seems oversized. This icon is used next to the name of each plugin allowing people to detach the plugin into a new window.
=> glade/dmm: Reconstruct UI file with Glade 3.38.2

plugins/dac_data_manager.c
- Add button to stop buffer transmission for DAC devices which do not offer DDS support (but offer buffer capabilities).
- Add enable/disable cyclic buffer button for DAC devices which do not offer DDS support (but offer buffer capabilities).
=> DAC Data Manager cyclic buffer support

plugins/ad9081.c, plugins/adrv9002.c
The DAC Manager holds a weak reference to the IIO context (passed by the plugin) which it uses to handle the dac devices (eg: creating buffers). In dac_data_manager_free(), the Manager will destroy any buffers that were created which means we cannot destroy the IIO context before calling this function...
While at it, reordered how resources are freed during the plugin destructor so that we free things in the reverse order they were created (as it should be typically done).
=> plugins: adrv9002: fix segfault with dac buffering

oscplot.c
The way we added images with GTK2 was no longer compatible with GTK3. These changes add images on menuitems (that show up on right-clicking on a device or a channel).
=> oscplot.c: bring back image creation for menuitems

osc.c
The GTK2 implementation was commented temporary (for build to pass) during transition to GTK3. These changes add a GTK3 implementation that reads the width and height of a GdkScreen.
=> osc: Re-enable getting screen width and height

oscplot.c
This was disabled temporary during the GTK2 to GTK3 transition because the way the color is represented has changed. Before, each color component was stored in a byte. Now the color component is a float.
=> oscplot.c: Reenable the saving and loading of channel color

oscplot.c
During the GTK2 to GTK3 transition this was disabled. These changes reenable it to work with GTK3.
=> oscplot: Reenable the functionality to capture a screenshot of the plot

oscplot.c
Don't search for math channels in an iio device.
=> oscplot.c: Fix crash when creating math channels

CMakeLists.txt
This is because rdynamic is a linker flag. And also there are reports that during build warnings(or errors) happend because of this flag being provided to compiler.
=> cmake: Move -rdynamic flag from compiler to linker

dialogs.c, iio_utils.h, osc.h, oscplot.c
Needed to compile with clang. Both of the "fixes" make sense. 
It might make sense to have a CI job to also compile things with clang. Compiling with more than one compiler is always a good thing as it allow us to catch more things.
=> clang fixes

CMakeLists.txt
The CMake version needs to be bumped to 3.13 in order to support the add_link_options CMake command. 
This will also eliminate the CMake Deprecation Warning.
=> CMakeLists: min. version increased to 3.13

.github/workflows/buildmingw.yml, CI/docker/build_mingw.sh, CI/docker/inside_docker.sh
build latest libiio, libad9361, libad9661 inside windows docker 
pass branch/tag/SHA for lib repos as environment variables when running the docker image in workflow file
This allows compiling and bundling the windows installer with the desired versions of libiio, libad9361, libad9661
=> Mingw-build: create osc installer using latest iio libs

osc.c, osc.h, oscplot.c, trigger_dialog.c
The bug where libiio would return error EIO in case the iio device supports a trigger but none is assigned, no longer exists in latest versions of libiio. Probably was fixed long time ago. However I found that on serial backend the EIO is being returned by iio_device_get_trigger() even though the intention was to report that iio device doesn't support/need a trigger. The expected behaviour is that 0 is returned and trigger argument is set to NULL. But this unhappy coincidence was forcing users to provide a trigger for an iio device that does not need one. It happened that no trigger was available making the users unable to ask for samples from the device. Note: this doesn't happend to all scenarios where serial backend is used. I have seen the issue only on 2 projects. And I have seen it …
=> Remove workaround when checking for a trigger of a device

plugins/ad9739a.c, plugins/dac_data_manager.c
Linked to [ADI Linux PR 2125](https://github.com/analogdevicesinc/linux/pull/2125).
=> ad9739a.c & dac_data_manager.c: Change name from "hpc" to "lpc"

plugins/spectrum_analyzer.c
When trying to start the spectrum analyzer from the plugin, any mismatch between the requested sampling rate and the set rate read back causes the plugin to fail to launch due to a `return false`.
On many systems, there is a small mismatch where `61440000` (default rate) will return `61439999`, causing a match failures. This change simply logs the mistmatch warning, but still allows the output window to be shown.
=> plugins: spectrum_analyser: Fix sampling freq check

plugins/cn0540.c
allocate enough space for channel labels with double digits and NULL 
add NULL for channels with double digits
this fixes segmentation fault which appears when running osc on ADI Kuiper Linux on Zynq Cora boards with the CN0540
=> plugins/cn0540: fix segmentation fault

osc.c, oscplot.c
do not print :
" Failed to check if device has trigger. Error:No such file or directory"
The message is misleading, as there is no error. It's just that the device doesn't have a trigger
=> remove error message for devices without triggers

plugins/cn0540.c
The plugin supports 8 GPIOs (as is the design of the CN0540 board).
With some minor customizations, more GPIOs can be adapted (for some extra controls).
When that happens, OSC will crash as 'gpio_ch[++idx].gpio = iio_device_find_channel()' will go beyond the size of the gpio_ch[] array.
So, a quick fix is to just allow more GPIOs (64 should be enough for anyone). But mainly, it would be guard against going above the size of the gpio_ch[] array.
=> plugins: cn0540: allow up to 64 GPIOs (one-bit-adc-dac) instances

CI/azure/build_osc_arm.sh, azure-pipelines.yml
- azure-pipelines will now pull the libiio, libad9361, libad9166 artifacts corresponding to the libiio-v0 API 
this will ensure that the CI will work for the current version of osc, until moving to libiio-v1
- added apt-get update to build_osc_arm script to prevent E: Failed to fetch package name error
=> Fix Azure CI

glade/oscplot.glade, oscplot.c
This includes the following fixes: 
- exapand channel list in save_as dialog so all channels are visible
- use allocation widget to get the position of osc plot window when screenshotting(saving to PNG)
- check data written to CSV,MAT,VSA files is coming only from input channels
- make sure only input channels are displayed in save_as list (temporary fix)
=> Fix save feature

plugins/adrv9002.c
The array in 'struct carrier_helper' needs to be increased to the max number of channels. The assumption of 3 being the max possible number is no longer true. After
commit a2c666aa9ac58 ("plugins: adrv9002: fix carrier handling"), we can have all ports moved to calibrated state using that helper struct (when all ports are on the same LO). Hence, we could run into an out of bounds access. On arch (as all packages and hence gtk are build with -fstack-clash-protection) we, at least, get the program aborted with stack smashing protection abort.
---
Note that on master we don't need the fix since commit 6639701cf348 implicitly fixed it.
=> plugins: adrv9002: fix out of bounds access

CI/docker/install_prep.sh
When creating directory hierarchy  for windows installer, copy xmls directory to the bin directory. This ensures that osc is able to find the xml files which produce the detailed SPI Reg Map. 
This fixes the issue where the detailed reg map is not visible on windows.
=> Fix Detailed SPI Reg Map on windows

xml_utils.c
Building osc in arch linux started to fail because of warnings being treated as errors:
"
error: implicit declaration of function ‘calloc’ [-Werror=implicit-function-declaration]
188 |                 text = (char *)calloc(1, sizeof(char)); /* Create an empty string */
|                                ^~~~~~
note: include ‘<stdlib.h>’ or provide a declaration of ‘calloc’
error: incompatible implicit declaration of built-in function ‘calloc’ [-Werror=builtin-declaration-mismatch]
"
The likely reason is that stdlib.h was somehow being indirectly included and maybe a change in libxml changed that. Hence, let's just explicitly include the needed header.
=> xml_utils: explicitly include <stdlib.h>

iio_widget.c, plugins/adrv9002.c
Fix warnings due to unused variables. This would fail compilation due to Werror...
=> Fix clang warnings

glade/adrv9002.glade, iio_utils.c, iio_utils.h, osc.c, plugins/adrv9002.c
Small series with some nit improvements and a fix for the adrv9002 plugin.
=> Fix adrv9002 plugin

plugins/adrv9002.c
Adrv9003 only has 1 TX. As such we should not try to update the other TX carrier value as that would lead to a segfault.
=> plugins: adrv9002: fix carrier handling for adrv9003

CMakeLists.txt
this flag enables compiling of osc with clang 
this will be removed once gdk threading issues are addressed
=> CMakeLists: add Wno-error=deprecated flag

dialogs.c, osc.c, oscplot.c, plugins/adrv9009.c, plugins/dac_data_manager.c, plugins/debug.c, plugins/scpi.c, styles.css
Replaced most deprecated gtk3 functions 
The threading methods gdk_threads_init, gdk_threads_enter, gdk_threads_leave will be addressed in a separate PR. These require a greater change within the application code.
=> Replace deprecated GTK functions

plugins/adrv9002.c
The device widgets were not being updated when pressing the reload button or when a new profile is loaded.
=> plugins: adrv9002: make sure to update device widgets

.github/workflows/buildmingw.yml
pull from main branches of libad9361 and libad9166 repos when building windows installer
=> CI: github windows workflow:  change libads to main branch

glade/adrv9002.glade, plugins/adrv9002.c
The profile gen was failing to create a configuration since some attributes cannot be read if the channel is disabled
=> adrv9002 plugin fix for disabled channels

osc.c
There are scenarios where a larger timeout is needed. For example, when using the UART interface, the bandwith is significantly lower than USB or Ethernet. When "capture_timeout" is read from a .ini file, the assigned value (e.g. "capture_timeout=5000") will overwrite the value that osc computes internally.
=> osc.c: Allow setting the capture timeout via .ini file

libini2.c, oscplot.c, phone_home.c
This PR makes sure that the sizeof argument to calloc is the second argument. New versions of gcc want to enforce this.
=> make sure the sizeof argument to calloc is the second argument.

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Persons specified in CODEOWNERS file will be automatically added as reviewers, whenever new PRs are opened, depending on affected folder.
In addition to Code Owners, other reviewers can be added to each PR. CODEOWNERS file can be different from one branch to another. All new PRs will require the approval of at least one code owner.
PULL_REQUEST_TEMPLATE.md will populate all new PR description field. Beside PR description, it contains a list of checkboxes, ensuring everyone follows the same guidelines and enforces best practices. Pull Request Template applies to PRs against all protected branches.
Both files got added in .github
=> Add CODEOWNERS and PULL_REQUEST_TEMPLATE files

osc.c, oscplot.c
- Make iio-oscilloscope plot (oscplot.c) and core (osc.c) lookup IIO DEVICES by label first. This would avoid issues where multiple IIO DEVICES with the same name exists. See https://github.com/analogdevicesinc/iio-oscilloscope/issues/480.
=> Fix plot not using device labels

dialogs.c
On MacOS there were some issues with the network iio_context scanning process. Inside libiio, some mutex locks are done during scanning. This blocks the UI thread and makes the app unusable. Moving into its own thread and creating a protected section (similar to calibration processes) should resolve this issue.
Besides these changes, iio-osc also needs some different fixes to get it working on MacOS (here are 2 dev branches on this matter by Cristina and Travis).
=> dialogs.c: move the scanning process into its own thread.

plugins/adrv9002.c
- validation failed if driver was "68.8.1" and profile gen was "v68.8.1", so we now check if they contain the same version substring
- added option to load profile even with API version mismatch
=> adrv9002: API version mismatch fix

oscplot.c
iio_device_get_trigger will return 0 on success, but if there is no device assigned to the trigger, the trigger pointer will be NULL. since the impulse generator menu sets the trigger, the condition if (ret == 0 && trigger) will not be satisfied. this resulted in the impulse generator menu being grayed out. Now, we will only check that the return value is 0, to see if our device needs a trigger, which will be configured in the menu. The renaming of the bool variable to needs_trigger is to avoid confusion.
=> Fix Impulse Generator Menu

plugins/dac_data_manager.c
The idea behind the fix is the following: due to libiio v1.x API changes the creation of the iio_buffer cannot be done too early. It needs a iio_mask and at least one channel to be enabled. The need to create the iio_buffer early was just to read one attribute about alignment, and to read the attribute only once.
The fix is to create the iio_buffer at the moment is needed and read the attribute right after the creation.
The effort for this fix started because osc was crashing at startup.
=> plugins/dac_data_manager: Create iio buffer at the right moment

iio_utils.c, iio_utils.h, iio_widget.c, plugins/CMakeLists.txt, plugins/fmcomms2.c
This re-enabled the 'fmcomms2' plugin and updates it to use libiio v1.x API.
Additionally, it adds some helpers for iio attributes reading and writing. The purpose of the helpers is to reduce duplicated code and improve code readability.
=> Libiio v1 support ad9361

plugins/CMakeLists.txt, plugins/ad9081.c, plugins/ad9084.c, plugins/ad9371.c, plugins/ad9371_adv.c, plugins/ad9739a.c, plugins/adrv9002.c, plugins/adrv9009.c, plugins/adrv9009_adv.c, plugins/daq2.c
Re-enable plugins: AD9081, AD9084, ADRV9002, AD9371, ADRV9009 and update them to use libiio v1.x.
Also, re-enable plugins: ad6676, fmcadc3, pr_config, cf_axi_tdd, xmw, ad5628_1.
=> Libiio v1 support more plugins

iio_widget.c, plugins/adrv9002.c
This PT has a fix for updating the ensm when the port mode is set to pin. But the main feature being added is to allow to control the ensm even when in pin mode (given that the drivers allows us to do that)
=> adrv9002 ensm improv

datatypes.h, osc.c, osc.h, oscplot.c
We need to keep just one channels mask across iio-osc. This is needed in order to be able to accurately count the number of enabled channels.
=> Libiio1 plot single channels mask

.github/workflows/buildmingw.yml
Github CI fails for MinGW builds due to a deprecated version.
=> ci/buildmingw.yml: fix deprecated version of upload-artifact

CMakeLists.txt, datatypes.h, osc.c, osc.h, oscmain.c, oscplot.c
Osc plot now uses libiio v1 API and data is captured with the iio_stream object.
=> Enable Osc Plot

plugins/CMakeLists.txt, plugins/fmcomms5.c
Apply required changes for fmcomms5 plugin to build with libiio V1.x.
=> plugins/fmcomms5: Reenable and update to libiio 1.x API

plugins/CMakeLists.txt, plugins/fmcomms2_adv.c
Reenable the 'fmcomms2_adv' plugin. This is only half done as it depends on the Oscplot which is currently WIP.
=> plugins/fmcomms2_adv: Reenable and update to libiio 1.x API

plugins/dac_data_manager.c
Instead of assuming a connected device will only have a maximum of 8 DMA channels, add a mechanism to dynamically convert data for all enabled channels.
This can be reproduced with a setup of ADRV9009 and FMCOMMS8 with all 8 TX channels enabled. Loading any file with all channels enabled will display "Waveform loaded successfully" but the DMA output will be 0. Doing the same with only 4 TX channels enabled will work properly.
=> plugins/dac_data_manager.c: dynamically convert data for enabled channels.

glade/oscplot.glade, oscplot.c
Get rid of GTK3 runtime warning each time an iio-osc plot is being created.
=> glade/oscplot: Fix runtime GTK3 warning when creating plot

oscplot.c
The current implementation of the math channel generator did not take into account the suffixes _i and _q, 
Now, we check whether the channels have any of the suffixes and ensure their names are properly stored in the channels list. 
This fixes issue https://github.com/analogdevicesinc/iio-oscilloscope/issues/451
=> Fix math feature

osc.c
The following error message was being displayed at startup: CRITICAL **: rx_update_device_sampling_freq: assertion 'device' failed
This was due to the existence of:
/sys/bus/iio/device/iio_sysfs_trigger
which doesn't have the 'name' attribute.
=> osc: Use device ID when name or label fails

.github/workflows/build_ubuntu_appimage.yml, .gitignore, CI/appimage_x86_64/.dockerignore, CI/appimage_x86_64/AppRun, CI/appimage_x86_64/build_osc.sh, CI/appimage_x86_64/create_appimage.sh, CI/appimage_x86_64/create_docker_image.sh, CI/appimage_x86_64/docker/Dockerfile, CI/appimage_x86_64/install_deps.sh, CI/appimage_x86_64/osc.desktop
Added Linux x86_64 AppImage support
=> CI x86 AppImage

iio_utils.c
Get rid of some redundant 'else' statements. No functional change intended.
=> iio_utils: cosmetic changes

osc.c
- Segmentation fault is happening, when trying to load the plugin ADRV9002, if none of this devices are found in the current context. Therefore I checked if the plugin_info is NULL to prevent a segmentation fault.
- If no adrv9002 are found, the plugin will not be loaded.
=> Fixed segmentation fault if no ADRV9002 device is found
