Makefile
datatypes.h
dialogs.c
libini/libini.c
math_expression_generator.h
osc.c
osc.h
oscplot.c
oscplot.h
plugins/AD7303.c
plugins/dac_data_manager.c
plugins/debug.c
plugins/motor_control.c
plugins/pr_config.c
plugins/scpi.c

There are no more warnings to be shown when compiling the project.

Fix warnings

---

math_expression_generator.h
osc.c
osc.h

Mostly just minor stuff I noticed when glancing at the math expressions code.

various clean ups for math expression functionality

---

adrv9009.glade
adrv9009_adv.glade
plugins/adrv9009.c

Some changes based on the latest kernel driver updates and defaults from the Talise API version: 3.5.0.2

Adrv9009 updates

---

osc.c
oscplot.c

This should fix the warnings reported in #93 
Unfortunately I don't have gcc-8 so can't verify that this is enough to fix all warnings that are generated by gcc-8.

Fix gcc8 warnings

---

plugins/dac_data_manager.c

The dac_data_manager module currently uses sscanf() to parse data files.
This has the problem that sscanf() takes the current locale into account
when parsing numbers like doubles. Depending on the local the decimal point
can either be a dot(.) or a comma(,).
This means that for locales that use a comma for the decimal point data
files which use a comma for separating the values on a line the file does
get parsed incorrectly and can not be loaded.
Fix this by using g_ascii_strtod() function to parse the values. It parses
the value as if the locale was "C". This means dots are used for the
decimal point.
Note that while there are locale independent variants of sscanf() each
platform has their own incompatible version. Hence we are creating our own
tokenizer that splits the line into its …

dac_data_manager: Ignore locale when parsing data files

---

datatypes.c
osc.c
oscplot.c
phone_home.c
plugins/dac_data_manager.c
plugins/dac_data_manager.h
plugins/fmcomms2.c
plugins/fmcomms5.c
xml_utils.c

This changeset implements some changes reported in  Codacy tool and cppcheck.
It's part 2 of PR #98 
The intent is to send small PRs to make things easier to review.

Code cleanups: part 2: implement cleanups Codacy & cppcheck

---

osc.c
plugins/fmcomms1.c

Remove un-needed initialization.
Remove always false condition check.

Minor code cleanups (from Codacy)

---

.travis.yml
CI/travis/make
CMakeLists.txt
Makefile
dialogs.c

build: handle non-git repo builds

---

plugins/dac_data_manager.c

DMA buffers typically have an alignment requirement for the buffer length.
Currently this alignment requirement is hardcoded for each platform in the
corresponding plugin.
Newer versions of the kernel will report the alignment requirements
associated with a device through the `length_align_bytes` property. If this
property is present read it and use its value instead of the hardcoded
value from the plugin.
This will allow the DAC data manager to adopt to changes in the alignment
requirements without having to update the plugin.

dac_data_manager: Consider device buffer length alignment requirements

---

glade/adrv9009.glade
plugins/adrv9009.c

plugins: adrv9009: Add support for ADRV9008-1 and ADRV9008-2

---

glade/adrv9009.glade
iio_widget.c
iio_widget.h
libini2.c
libini2.h
osc.c
osc.h
plugins/dac_data_manager.c
plugins/dac_data_manager.h

Adding a couple of helpers that will be required for the implementation of the new plugin which will support multiple adrv9009 devices.
I've also squeezed a couple of small fixes.

Helpers and fixes

---

plugins/adrv9009.c

Finish the TODOs left in adrv9909.c that relate to the saving and restoring of plugin profile.

Adrv9009 complete save restore

---

plugins/spectrum_analyzer.c

This way we avoid comparing floating point values which is not a reliable thing to do anyway.
This fixes an issue that happens on OpenSuse Leap 42.3 where such a float comparison fails (61.44 != 61.39999).

Spectrum Analyzer: Use integer values when working with sample rates

---

glade/lidar.glade

plugins/lidar: Change ADP Bias lower limit to prevent negativ raw value

---

oscplot.c

oscplot: Prevent enabling/disabling the channel if it is greyed out

---

glade/lidar.glade

plugins/lidar: Make Tilt voltage go from 0 to 5V

---

osc.c

Trigger fixes

---

CI/travis/before_install_linux
osc.c
osc.h
plugins/CMakeLists.txt
plugins/scpi.c

And make them build on OS X as well.

plugins/cmake: Include SpectrumAnalyzer, SCPI plugins into the project

---

oscplot.c

Fix edge case quadratic interp peaks

---

oscplot.c

oscplot.c: Fix segfault when enabling markers in frequency domain

---

plugins/lidar.c

According to this Linux change: https://github.com/analogdevicesinc/linux/commit/e167f598d76ba4e83d64ef6712e8e5120ce412f5

plugins: lidar: Update PULSE_CAPTURE_DEV value

---

Makefile
glade/cn0511.glade
plugins/CMakeLists.txt
plugins/cn0511.c

The cn0511 plugin can be now merged with github (was previously on bitbucket)...

plugins: cn0511: Support cn0511 cape

---

Makefile
glade/ad9081.glade
plugins/CMakeLists.txt
plugins/ad9081.c
plugins/dac_data_manager.c

Let's start review and merge this. There is still some functionally that needs to be added, but we'll do this later on.

AD9081 plugin dev

---

dialogs.c
iio_widget.c
oscplot.c
plugins/ad9371.c
plugins/adrv9009.c
plugins/debug.c
plugins/fmcomms1.c
plugins/fmcomms2.c
plugins/fmcomms5.c
plugins/scpi.c
trigger_dialog.c

osc: Free strings returned by gtk_combo_box_text_get_active_text()

---

plugins/fmcomms2.c

Ad936x plugin fix crash

---

CI/appveyor/build.sh.inc

CI/appveyor: Keep the icons folder

---

glade/adrv9002.glade
plugins/adrv9002.c

This PR adds support for TX NCO support and some minor enhancements...

Adrv9001 misc

---

osc.c

osc: Try to recapture samples when encountering error: broken pipe

---

CMakeLists.txt
dialogs.c
glade/osc.glade

this will update the connect dialog box, so handles discovery easier for people, putting local, usb and IP contexts in a pull down, but allowing by hand manual, or serial context. Let me know if there are any issues.

Connect dialog updates

---

glade/oscplot.glade
oscplot.c

This can be handy when there are many channels.
Addresses #162

oscplot: Add option to enable/disable all channels at once

---

plugins/adrv9009.c

In general this HMC7044 direct register write is a bad idea.
Make sure this is only done in case of continous SYSREF and also
inform about it, in case this is undesired.

plugins: adrv9009: skip multichip_sync() for JESD204-FSM enabled setups

---

datatypes.h
glade/oscplot.glade
oscplot.c

This allows us to see a few different aspects when looking at some of
the CW tests we are doing on the SOM.
Also make the number of samples more dynamic - so we can get more FFT
resolution.
Signed-off-by: Robin Getz <robin.getz@analog.com>

fft: add the ability to change window functions for the fft.

---

glade/cn0511.glade

plugins: cn0511: Use float for sampling freq spinbutton

---

oscplot.c

When running on the GUI, you can't see the fps calculation, so display
it in the window.
Also remove it from printing on the console, since that is annoying.
Signed-off-by: Robin Getz <robin.getz@analog.com>

oscplot.c: move the fps display to the GUI

---

plugins/cn0511.c

plugins: cn0511: Make sure FIR85 filter is enabled by default

---

phone_home.c

Phone home dont disable cert verification

---

plugins/adrv9002.c
plugins/adrv9009.c
plugins/adrv9009_adv.c
plugins/cn0357.c
plugins/cn0508.c
plugins/cn0511.c
plugins/daq2.c
plugins/debug.c
plugins/dmm.c
plugins/fmcadc3.c
plugins/fmcomms1.c
plugins/fmcomms11.c
plugins/fmcomms2.c
plugins/fmcomms2_adv.c
plugins/fmcomms5.c
plugins/fmcomms6.c
plugins/generic_dac.c
plugins/lidar.c
plugins/motor_control.c
plugins/pr_config.c
plugins/spectrum_analyzer.c

This PR is a follow up on #276 . Since the changes are pretty simple and easy to review, I'm adding all the patches in one PR. I want to enforce that I'm only fixing the most obvious leaks and not going into too much details on the plugins init function.

Plugins init cleanup2

---

dialogs.c
glade/ad9081.glade
glade/adrv9002.glade
glade/cn0540.glade
phone_home.c
plugins/ad9081.c
plugins/adrv9002.c
plugins/adrv9009.c
plugins/adrv9009_adv.c
plugins/cn0357.c
plugins/cn0508.c
plugins/cn0511.c
plugins/cn0540.c
plugins/daq2.c
plugins/debug.c
plugins/dmm.c
plugins/fmcadc3.c
plugins/fmcomms1.c
plugins/fmcomms11.c
plugins/fmcomms2.c
plugins/fmcomms2_adv.c
plugins/fmcomms5.c
plugins/fmcomms6.c
plugins/generic_dac.c
plugins/lidar.c
plugins/motor_control.c
plugins/pr_config.c
plugins/spectrum_analyzer.c

There are some fixes which should be in 2019_R2 wondering if there is anything which must not be.
@nunojsa is the navassa stream loading support causing issues in case the driver doesn't (yet) support it?

Merge master 2019 r2

---

glade/ad9081.glade

glade/ad9081.glade: Change DSA text label

---

plugins/dac_data_manager.c

The goal of this change is to handle the frequency attr change for the I type channels. In single/dual tone modes, the Q channel is not visible to the user and the plugin automatically changes the gtk widget causing its signal to be called and thus, changing the value in the device. The problem is that for some frequency values, we won't get exactly what we tried to set (due to integer approximations in the driver) which means that 'widget->update(widget)' called from 'iio_widget_save()' will trigger
another gtk signal to set the frequency on the Q channel for the value we got from the driver. Thus, we will end up with slightly different setting in the I and Q channels. With this change, we make use of the '*_block_signals_by_data' to save the widget value and make sure that …

plugins: dac_data_manager: fix I and Q frequency mismatch

---

glade/adrv9002.glade
plugins/adrv9002.c

This PR adds support for:
* reading the profile attribute;
* support for the bbdc attribute;
* support for ORx controls.

adrv9001 new features

---

glade/adrv9002.glade
plugins/adrv9002.c

Improvements and minor fixes for the adrv9002 plugin

adrv9002 misc improvements

---

plugins/adrv9002.c

Handling the carrier frequency is not really straight because it looks
like we have 4 independent controls when in reality they are not, since
the device only has 2 LOs. It all the depends on the LO mappings present in
the current profile. First, the only way to guarantee that a carrier is actually applied (PLL
re-tunes) is if all ports on the same LO, are moved into the calibrated
state before changing it. Not doing so means that we may end up in an
inconsistent state. For instance, consider the following steps in a FDD
profile where RX1=RX2=LO1 (assuming both ports start at 2.4GHz):
1. Move RX1 carrier to 2.45GHz -> LO1 re-tunes
2. Move RX1 back to 2.4GHz -> LO1 does not re-tune and our carrier is at
2.45GHz
With the above steps we are left with both ports, __apparently__, at
2.45GHz …

plugins: adrv9002: improve carrier handling

---

plugins/adrv9002.c

This patch makes sure the dds gets into a consistent block with the rest
of the plugin (dds1 aligned with TX1 and dds2 with TX2). This is done by
checking the next character after the name "axi-adrv9002-tx" (as this is
the pattern we use to look for this devices). If we see a digit, then we
assume that it is the DDS2 and it should be under TX2 settings. If not a
digit, it's TX1. Naturally there's a chance for this to break if the
device name changes in some ways, but we do need to assume some "contracts"
with the name format otherwise this could get more complicated than it
needs to be.

plugins: adrv9002: fix inconsistent labels under Transmit/DDS block

---

iio_utils.c
plugins/cf_axi_tdd.c

Fix TDD plugin which was not loading. With this patch we are now using IIO labels to match the devices...

Fix axi core tdd

---

glade/adrv9009_adv.glade

Updated limit from the latest:
"Profile Configuration Tool User Guide for the
ADRV9008-1, ADRV9008-2, and ADRV9009"

glade/adrv9009_adv.glade: Update RX/TX/ORX profile adjustment limits

---

dialogs.c
osc.c

The main purpose of this is to change to the way we check for a broken connection with IIOD as that changed in libiio. In the process some misc fixes and mainly coding style improvements were done.
Adding @pcercuei as a reviewer so that he can ack if the new method is in accordance with his suggestion...

Fix osc net connection

---

glade/adrv9002.glade
plugins/adrv9002.c

Typically, knowing the API version is helpful to identify compatible profiles to load. The second patch is not related but was a small visual enhancement done while working on the API report.

adrv9002 api version

---

plugins/dac_data_manager.c

In case the DAC device does not offer DDS support, but it offers buffer capabilities, show DAC buffer settings.

plugins:dac_data_manager: Add support for devices without DDS

---

CMakeLists.txt
appveyor.yml
oscplot.c
plugins/AD7303.c
plugins/block_diagram.h
plugins/cn0540.c
plugins/dac_data_manager.c
plugins/dac_data_manager.h
plugins/scpi.c
styles.css

replaced deprecated widgets
replaced deprecated variable types
fixed plugins 
TO DO: 
update all glade files to match new widget types and hierarchy

Gtk3 transition initial changes

---

plugins/debug.c

This adds read/write support for IIO debugfs attributes.

plugins: debug: Support for IIO debugfs attributes

---

plugins/adrv9002.c

Main goal of the PR is to add support for adr9003 which does not have TX2. While at it, improvements and fixes were also added.

adrv9003 support and some fixes and improvements

---

glade/adrv9002.glade
plugins/adrv9002.c

This PR brings the adr9002 plugins into gtk3 (in terms of glades changes) and also improves in accordance to a change being also done in the driver.
On top of this, it moves the plugins to public widget APIs that were added in the meantime...

adrv9002 improvements

---

CI/docker/inside_docker.sh

sets IIO-Oscilloscope version when creating windows installers

Set osc version in windows installer

---

.github/workflows/buildmingw.yml
CI/docker/build_mingw.sh
CI/docker/inside_docker.sh

- mount osc source folder and artifact folder as volumes on docker container 
- use scripts from osc source folder to build the application and the windows installer
- bump github actions version to v3

Fix mingw build workflow

---

CMakeLists.txt
cmake_uninstall.cmake.in

All project files can now be removed from their install location using **make uninstall**

Add uninstall target

---

glade/adrv9002.glade
plugins/adrv9002.c

The first patches are just in preparation for initial calibrations. This follows the work done in:
https://github.com/analogdevicesinc/linux/pull/2228
So, better wait for that PULL to be merged first.

add adrv9002 initial calibrations

---

libini2.c
oscplot.c
phone_home.c

new versions of gcc want to enforce this
(cherry picked from commit 565cade20566d50adec7be191a6dd7b21217f878)

make sure the sizeof argument to calloc is the second argument.

---

iio_utils.c
iio_utils.h

Add additional utils that I found useful while re-enabling more plugins

utils: Add more helpers for reading/writing iio attributes

---

glade/ad9084.glade

Each spinbuttons needs it's own adjustment.
Each spinbuttons needs it's own adjustment.

glade/ad9084.glade: Fix connection of adjustments to spinbuttons

---

iio_utils.c
iio_utils.h

Add helpers to read/write dev attributes of type bool

utils: Add helpers to read/write dev attributes of type bool

---

osc.c

when the sampling freq is a channel specific attribute, the effective sampling freq is calculated depending on the sampling frequencies of each enabled channel
this also ensures effective capture timeout calculation
fixes issue https://github.com/analogdevicesinc/iio-oscilloscope/issues/489

Fix read_sampling_frequency

---

osc.c

Fix saving and loading the context uri in .ini file.

osc: Update saving & loading uri from .ini
